import React, { useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { Wand2, Save, FileText } from 'lucide-react';
import toast from 'react-hot-toast';

const Templates = () => {
  const { token } = useAuth();
  const [prompt, setPrompt] = useState('');
  const [subject, setSubject] = useState('');
  const [content, setContent] = useState('');
  const [templateName, setTemplateName] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const generateWithAI = async () => {
    if (!prompt) return toast.error("Please describe what you want the email to be about.");
    setIsGenerating(true);
    try {
      const res = await axios.post('http://localhost:5001/api/ai/generate', { prompt }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSubject(res.data.subject);
      setContent(res.data.content);
      toast.success("Content generated by AI!");
    } catch (err) {
      toast.error("Failed to generate content.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!content) return toast.error("Nothing to save!");
    try {
      await axios.post('http://localhost:5001/api/templates', { name: templateName || "AI Generated Template", subject, htmlContent: content }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      toast.success("Template saved successfully to your Directory!");
      setTemplateName('');
    } catch(err) {
      toast.error("Failed to save template.");
    }
  };

  return (
    <div className="animate-fade">
      <header style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>AI Template Builder</h1>
        <p style={{ color: 'var(--text-muted)' }}>Describe what you want to say, and let AI write the perfect email.</p>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        {/* Left Side: Generator */}
        <div className="glass-panel" style={{ padding: '2rem' }}>
          <h3 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}><Wand2 size={20} color="#ec4899" /> Prompt Engine</h3>
          <textarea 
            value={prompt} onChange={(e) => setPrompt(e.target.value)}
            placeholder="E.g., Write a welcome email for new users joining OmniReach, emphasizing our real-time tracking features."
            style={{ width: '100%', height: '150px', padding: '15px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: 'white', outline: 'none', resize: 'none', marginBottom: '1rem' }}
          />
          <button className="btn-primary" style={{ width: '100%' }} onClick={generateWithAI} disabled={isGenerating}>
            {isGenerating ? "Synthesizing..." : "Generate Email"}
          </button>
        </div>

        {/* Right Side: Preview Editor */}
        <div className="glass-panel" style={{ padding: '2rem', display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><FileText size={20} color="#6366f1" /> Editor</h3>
            <input type="text" placeholder="Template Save Name" value={templateName} onChange={e => setTemplateName(e.target.value)} style={{ padding: '8px 12px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '6px', color: 'white', outline: 'none' }} />
          </div>
          
          <label style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '4px' }}>Subject Line</label>
          <input type="text" value={subject} onChange={(e) => setSubject(e.target.value)} style={{ width: '100%', padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: 'white', outline: 'none', marginBottom: '1.5rem' }} />

          <label style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '4px' }}>HTML Content</label>
          <textarea value={content} onChange={(e) => setContent(e.target.value)} style={{ width: '100%', flex: 1, minHeight: '300px', padding: '15px', background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: 'white', outline: 'none', resize: 'none', fontFamily: 'monospace' }} />

          <button style={{ marginTop: '1.5rem', background: 'rgba(16, 185, 129, 0.2)', color: '#10b981', border: '1px solid rgba(16, 185, 129, 0.5)', padding: '10px', borderRadius: '8px', fontWeight: 600, display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px', cursor: 'pointer' }} onClick={handleSave}>
            <Save size={18} /> Save Template
          </button>
        </div>
      </div>
    </div>
  );
};

export default Templates;
